-- 门票类型表
CREATE TABLE IF NOT EXISTS `ski_ticket_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '票种ID',
  `ticket_code` VARCHAR(50) NOT NULL COMMENT '票种编码',
  `ticket_name` VARCHAR(100) NOT NULL COMMENT '票种名称',
  `ticket_type` VARCHAR(20) NOT NULL COMMENT '票种类型（1全天票 2半天票 3夜场票 4季票 5年票）',
  `price` DECIMAL(10,2) NOT NULL COMMENT '价格',
  `valid_days` INT(11) DEFAULT 1 COMMENT '有效期（天）',
  `description` TEXT COMMENT '票种描述',
  `image_url` VARCHAR(500) COMMENT '票种图片',
  `status` CHAR(1) DEFAULT '0' COMMENT '状态（0正常 1停用）',
  `sort_order` INT(11) DEFAULT 0 COMMENT '排序',
  `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ticket_code` (`ticket_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门票类型表';

-- 门票订单表
CREATE TABLE IF NOT EXISTS `ski_ticket_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单号',
  `ticket_type_id` BIGINT(20) NOT NULL COMMENT '票种ID',
  `ticket_type_name` VARCHAR(100) COMMENT '票种名称',
  `visitor_name` VARCHAR(50) NOT NULL COMMENT '游客姓名',
  `visitor_phone` VARCHAR(20) NOT NULL COMMENT '游客手机号',
  `visitor_id_card` VARCHAR(18) COMMENT '游客身份证号',
  `ticket_count` INT(11) NOT NULL DEFAULT 1 COMMENT '购票数量',
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '总金额',
  `paid_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '已支付金额',
  `booking_date` DATE NOT NULL COMMENT '预订日期',
  `use_date` DATE COMMENT '使用日期',
  `order_status` VARCHAR(20) DEFAULT '0' COMMENT '订单状态（0待支付 1已支付 2已使用 3已退票 4已取消）',
  `payment_method` VARCHAR(20) COMMENT '支付方式（1现金 2微信 3支付宝 4银行卡）',
  `payment_time` DATETIME COMMENT '支付时间',
  `refund_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '退款金额',
  `refund_reason` VARCHAR(500) COMMENT '退款原因',
  `refund_time` DATETIME COMMENT '退款时间',
  `refund_status` VARCHAR(20) DEFAULT '0' COMMENT '退款状态（0无退款 1退款中 2已退款 3退款失败）',
  `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_ticket_type_id` (`ticket_type_id`),
  KEY `idx_visitor_phone` (`visitor_phone`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_booking_date` (`booking_date`),
  CONSTRAINT `fk_ticket_order_type` FOREIGN KEY (`ticket_type_id`) REFERENCES `ski_ticket_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门票订单表';
