-- 通知公告模拟数据
-- 注意：执行前请确保已创建 ski_notice 表

-- 插入通知公告数据
INSERT INTO `ski_notice` (`notice_title`, `notice_type`, `notice_content`, `status`, `publish_time`, `expire_time`, `priority`, `read_count`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES
('欢迎来到滑雪场！', '2', '尊敬的游客朋友们，欢迎来到我们的滑雪场！为了确保您的安全，请务必遵守以下规定：\n1. 请佩戴好安全帽和护具\n2. 遵守雪道规则，不要逆行\n3. 初学者请在指定区域练习\n4. 如遇紧急情况，请及时联系工作人员\n\n祝您滑雪愉快！', '0', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1, 256, 'admin', NOW(), 'admin', NOW(), '欢迎公告'),
('雪道维护通知', '1', '各位游客请注意，由于天气原因，1号雪道将于明天（2026-02-06）上午8:00-12:00进行维护作业，期间将暂停开放。\n\n给您带来的不便，我们深表歉意。其他雪道正常开放，欢迎您前往其他雪道体验。\n\n如有疑问，请联系客服热线：400-123-4567', '0', NOW(), DATE_ADD(NOW(), INTERVAL 3 DAY), 2, 189, 'admin', NOW(), 'admin', NOW(), '紧急维护通知'),
('春节优惠活动', '2', '🎉 春节特惠活动开始啦！\n\n活动时间：2026-02-08 至 2026-02-15\n\n活动内容：\n1. 全天票享受8折优惠\n2. 购买季票赠送雪具租赁券\n3. 家庭套餐（2大1小）立减100元\n4. 会员充值满500送100\n\n数量有限，先到先得！详情请咨询前台或致电客服。', '0', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_ADD(NOW(), INTERVAL 10 DAY), 1, 342, 'admin', DATE_SUB(NOW(), INTERVAL 2 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 2 DAY), '春节活动公告'),
('安全提示', '1', '重要安全提示：\n\n近日天气转暖，部分雪道可能出现结冰现象。请各位游客：\n1. 减速慢行，注意安全\n2. 保持安全距离\n3. 如发现危险情况，请立即报告工作人员\n4. 建议佩戴护目镜，防止雪盲\n\n安全第一，快乐滑雪！', '0', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 7 DAY), 2, 156, 'admin', DATE_SUB(NOW(), INTERVAL 1 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 1 DAY), '安全提示'),
('教练预约服务上线', '2', '好消息！我们的在线教练预约服务正式上线了！\n\n现在您可以通过以下方式预约专业滑雪教练：\n1. 登录系统，进入"教练预约"模块\n2. 选择您心仪的教练和时间段\n3. 在线支付预约费用\n4. 按时到达指定地点上课\n\n教练团队介绍：\n- 初级教练：适合零基础学员\n- 中级教练：适合有一定基础的学员\n- 高级教练：适合进阶提升\n\n预约热线：400-123-4567', '0', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(NOW(), INTERVAL 60 DAY), 0, 89, 'admin', DATE_SUB(NOW(), INTERVAL 5 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 5 DAY), '服务上线公告'),
('雪具租赁优惠', '1', '雪具租赁优惠活动：\n\n即日起至本月底，雪具租赁享受以下优惠：\n- 单次租赁：8折优惠\n- 全天租赁：7折优惠\n- 连续租赁3天以上：6折优惠\n\n租赁物品包括：\n- 滑雪板（单板/双板）\n- 滑雪杖\n- 滑雪靴\n- 安全帽\n- 护具套装\n\n所有设备均经过专业维护，安全可靠！', '0', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 20 DAY), 0, 124, 'admin', DATE_SUB(NOW(), INTERVAL 3 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 3 DAY), '租赁优惠通知'),
('天气预警', '1', '⚠️ 天气预警通知\n\n根据气象部门预报，未来3天将有大风天气，风力可达6-7级。\n\n为确保游客安全，我们将采取以下措施：\n1. 部分高难度雪道可能临时关闭\n2. 缆车运营时间可能调整\n3. 建议游客关注天气变化，合理安排行程\n\n我们会根据实际情况及时调整运营安排，请关注最新通知。\n\n给您带来的不便，敬请谅解！', '0', NOW(), DATE_ADD(NOW(), INTERVAL 3 DAY), 2, 78, 'admin', NOW(), 'admin', NOW(), '天气预警'),
('会员积分系统升级', '2', '会员积分系统全新升级！\n\n新功能：\n1. 消费即可获得积分，1元=1积分\n2. 积分可兑换雪票、租赁券等\n3. 生日月双倍积分\n4. 推荐好友注册，双方各得100积分\n\n积分兑换规则：\n- 100积分 = 10元优惠券\n- 500积分 = 全天票一张\n- 1000积分 = 季票8折优惠\n\n更多优惠，敬请期待！', '0', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), 0, 201, 'admin', DATE_SUB(NOW(), INTERVAL 7 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 7 DAY), '会员系统升级'),
('停车场使用说明', '1', '停车场使用说明：\n\n1. 停车场位置：滑雪场正门右侧，可容纳200辆车\n2. 收费标准：\n   - 前2小时：免费\n   - 2-6小时：10元\n   - 6小时以上：20元\n   - 会员车辆：免费（需提前登记）\n3. 停车时间：每日6:00-22:00\n4. 注意事项：\n   - 请锁好车门，贵重物品请随身携带\n   - 按指定位置停车，不要占用消防通道\n   - 如遇问题，请联系停车场管理员\n\n感谢您的配合！', '0', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 180 DAY), 0, 67, 'admin', DATE_SUB(NOW(), INTERVAL 10 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 10 DAY), '停车场说明'),
('雪场开放时间调整', '1', '雪场开放时间调整通知：\n\n自2026年2月1日起，雪场开放时间调整为：\n\n平日（周一至周五）：\n- 开放时间：8:00-18:00\n- 夜场时间：18:00-22:00（仅限指定雪道）\n\n周末及节假日：\n- 开放时间：7:00-20:00\n- 夜场时间：20:00-23:00（仅限指定雪道）\n\n请各位游客合理安排时间，祝您滑雪愉快！', '0', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(NOW(), INTERVAL 60 DAY), 0, 145, 'admin', DATE_SUB(NOW(), INTERVAL 5 DAY), 'admin', DATE_SUB(NOW(), INTERVAL 5 DAY), '时间调整通知');
