-- 物资管理表
CREATE TABLE IF NOT EXISTS `ski_material` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '物资ID',
  `material_code` varchar(50) NOT NULL COMMENT '物资编码',
  `material_name` varchar(100) NOT NULL COMMENT '物资名称',
  `material_type` varchar(50) DEFAULT NULL COMMENT '物资类型（1急救药品 2医疗用品 3其他）',
  `specification` varchar(100) DEFAULT NULL COMMENT '规格型号',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位（盒、瓶、支等）',
  `manufacturer` varchar(100) DEFAULT NULL COMMENT '生产厂家',
  `batch_number` varchar(50) DEFAULT NULL COMMENT '批次号',
  `production_date` date DEFAULT NULL COMMENT '生产日期',
  `expiry_date` date DEFAULT NULL COMMENT '有效期至',
  `safety_stock` int(11) DEFAULT '0' COMMENT '安全库存',
  `current_stock` int(11) DEFAULT '0' COMMENT '当前库存',
  `unit_price` decimal(10,2) DEFAULT '0.00' COMMENT '单价',
  `storage_location` varchar(100) DEFAULT NULL COMMENT '存放位置',
  `status` varchar(20) DEFAULT '0' COMMENT '状态（0正常 1停用）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_material_code` (`material_code`),
  KEY `idx_material_name` (`material_name`),
  KEY `idx_material_type` (`material_type`),
  KEY `idx_expiry_date` (`expiry_date`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物资管理表';

-- 出入库记录表
CREATE TABLE IF NOT EXISTS `ski_material_stock` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `material_id` bigint(20) NOT NULL COMMENT '物资ID',
  `material_code` varchar(50) DEFAULT NULL COMMENT '物资编码（冗余）',
  `material_name` varchar(100) DEFAULT NULL COMMENT '物资名称（冗余）',
  `operation_type` varchar(20) NOT NULL COMMENT '操作类型（1入库 2出库）',
  `quantity` int(11) NOT NULL COMMENT '数量',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT '单价',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '总金额',
  `batch_number` varchar(50) DEFAULT NULL COMMENT '批次号',
  `production_date` date DEFAULT NULL COMMENT '生产日期',
  `expiry_date` date DEFAULT NULL COMMENT '有效期至',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `operation_time` datetime DEFAULT NULL COMMENT '操作时间',
  `supplier` varchar(100) DEFAULT NULL COMMENT '供应商（入库时）',
  `purpose` varchar(200) DEFAULT NULL COMMENT '用途说明（出库时）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_operation_type` (`operation_type`),
  KEY `idx_operation_time` (`operation_time`),
  KEY `idx_expiry_date` (`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出入库记录表';

-- 领用记录表
CREATE TABLE IF NOT EXISTS `ski_material_usage` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '领用ID',
  `material_id` bigint(20) NOT NULL COMMENT '物资ID',
  `material_code` varchar(50) DEFAULT NULL COMMENT '物资编码（冗余）',
  `material_name` varchar(100) DEFAULT NULL COMMENT '物资名称（冗余）',
  `quantity` int(11) NOT NULL COMMENT '领用数量',
  `user_id` bigint(20) DEFAULT NULL COMMENT '领用人ID',
  `user_name` varchar(64) DEFAULT NULL COMMENT '领用人姓名',
  `department` varchar(100) DEFAULT NULL COMMENT '所属部门',
  `usage_purpose` varchar(200) DEFAULT NULL COMMENT '用途说明',
  `usage_time` datetime DEFAULT NULL COMMENT '领用时间',
  `return_time` datetime DEFAULT NULL COMMENT '归还时间',
  `return_status` varchar(20) DEFAULT '0' COMMENT '归还状态（0未归还 1已归还）',
  `approver_id` bigint(20) DEFAULT NULL COMMENT '审批人ID',
  `approver_name` varchar(64) DEFAULT NULL COMMENT '审批人姓名',
  `approval_status` varchar(20) DEFAULT '0' COMMENT '审批状态（0待审批 1已批准 2已拒绝）',
  `approval_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approval_remark` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_usage_time` (`usage_time`),
  KEY `idx_return_status` (`return_status`),
  KEY `idx_approval_status` (`approval_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='领用记录表';
